name: Generate Snake

on:
  # Executa automaticamente a cada 24 horas
  schedule:
    - cron: "0 0 * * *" 
  
  # Permite rodar manualmente na aba "Actions"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Generate Snake
        uses: Platane/snk@v3
        with:
          # Seu usuário do GitHub
          github_user_name: Cawlino
          # Onde os arquivos GIF/SVG serão salvos
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      - name: Push to the output branch
        uses: crazy-max/gh-action-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
